id: 1f64243b122746879661344483ddb916
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_335-The_Sutra_on_the_Ringing_Staff-v2
  language: en-us
  author: ''
  volume: {}
